SECTION_QUESTION = {"Title": ["The title of the presentation was clear.", "The title reflected well the content of the presentation."],
                    "Software engineering problem (Research question / goal)": ["The main problem (research question/goal) was stated explicitly.",
                                                                                "The main problem (research question/goal) was clearly explained, with the current audience in mind.",
                                                                                "I understood the SE problem.",
                                                                                "I understood the relevance of addressing the problem.",
                                                                                "I found the problem interesting."],
                    "Proposal / Study / Solution": ["It was clearly stated.",
                                                    "The presenter clearly related it to the SE problem (and research question/goal).",
                                                    "I understood the (expected) contributions of the study.",
                                                    "The presenter convinced me of the significance of the contribution(s)."],
                    "Methodology": ["The methodology was well structured.",
                                    "The presenter clearly related the methodology to the problem (research question/goal).",
                                    "Results were clearly and adequately presented.",
                                    "Limitations/gaps of existing work (or traditional techinique) were clearly presented.",
                                    "Results and limitations were clearly related to the research question."],
                    "Presentation": ["The presenter seems to have rehearsed.",
                                     "The presentation was structured in a logical way.",
                                     "The presentation was well designed (sliders are clear, visually appealing, no typos etc.).",
                                     "The presentation was well delivered.",
                                     "The presenter used clear and accessible language (i.e. avoided unnecessary jargon and provided the necessary definitions).",
                                     "The presenter transitioned between the main parts of the presentation clearly and effectively.",
                                     "The presenter was credible. (I believe he/she knows what he/she is talking about.)",
                                     "The presenter was confident.The presenter connected with the audience.",
                                     "The presenter used pacing, pausing, gestures and movement effectively and appropriately.",
                                     "The presenter answered the questions appropriate."]}
