# Generated by Django 3.2 on 2024-02-28 06:54

import app.gamification.models.course
import app.gamification.models.user
from django.conf import settings
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('andrew_id', models.CharField(error_messages={'unique': 'A user with that andrew id already exists.'}, help_text='Required. 150 characters or fewer. Lower case letters only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Andrew ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), app.gamification.models.user.FileSizeValidator(max_size=5242880)], verbose_name='profile picture')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=True, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data joined')),
                ('exp', models.IntegerField(blank=True, default=0, null=True)),
                ('daily_streak', models.IntegerField(blank=True, default=0, null=True, verbose_name='daily streak')),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last login')),
                ('gamification_mode', models.BooleanField(blank=True, default=True, null=True, verbose_name='gamification mode')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', app.gamification.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='upload time')),
                ('file', models.FileField(blank=True, help_text='Upload a PDF file.', upload_to='assignment_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='assignment file')),
            ],
            options={
                'verbose_name': 'artifact',
                'verbose_name_plural': 'artifacts',
                'db_table': 'artifact',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(blank=True, max_length=150, verbose_name='assignment name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('assignment_type', models.TextField(blank=True, choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Individual')),
                ('submission_type', models.TextField(blank=True, choices=[('File', 'File'), ('URL', 'Url'), ('Text', 'Text')], default='File')),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('date_released', models.DateTimeField(blank=True, null=True, verbose_name='date released')),
                ('date_due', models.DateTimeField(blank=True, null=True, verbose_name='date due')),
                ('review_assign_policy', models.TextField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A')),
                ('min_reviewers', models.IntegerField(blank=True, default=2, null=True)),
                ('ipsatization_min', models.IntegerField(blank=True, default=80, null=True)),
                ('ipsatization_max', models.IntegerField(blank=True, default=100, null=True)),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField(default='', verbose_name='operation')),
                ('points', models.IntegerField(default=0, null=True, verbose_name='points')),
            ],
            options={
                'verbose_name': 'behaviors',
                'verbose_name_plural': 'behaviors',
                'db_table': 'behaviors',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(blank=True, max_length=150, verbose_name='course number')),
                ('course_name', models.CharField(blank=True, max_length=150, verbose_name='course name')),
                ('syllabus', models.TextField(blank=True, verbose_name='syllabus')),
                ('semester', models.CharField(blank=True, max_length=150, verbose_name='semester')),
                ('visible', models.BooleanField(default=False, verbose_name='visible')),
                ('picture', models.ImageField(blank=True, upload_to=app.gamification.models.course.Course.photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), app.gamification.models.course.FileSizeValidator(max_size=5242880)], verbose_name='course picture')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.course')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('name', models.CharField(default='Default Survey', max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.assignment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback survey',
                'verbose_name_plural': 'feedback surveys',
                'db_table': 'feedback_survey',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('points', models.IntegerField(default=0, null=True, verbose_name='points')),
                ('reward_type', models.TextField(choices=[('Other', 'Other'), ('Late Submission', 'Late Submission'), ('Bonus', 'Bonus')], default='Other')),
                ('inventory', models.IntegerField(blank=True, default=-1, null=True, verbose_name='inventory')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='is active')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='rewards', verbose_name='reward_picture')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.course')),
            ],
            options={
                'verbose_name': 'reward',
                'verbose_name_plural': 'rewards',
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='ArtifactFeedback',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamification.answer')),
                ('page', models.CharField(blank=True, max_length=150, verbose_name='page')),
            ],
            options={
                'verbose_name': 'artifact_feedback',
                'verbose_name_plural': 'artifact_feedback',
                'db_table': 'artifact_feedback',
            },
            bases=('gamification.answer',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamification.entity')),
            ],
            options={
                'verbose_name': 'individual',
                'verbose_name_plural': 'individuals',
                'db_table': 'individuals',
            },
            bases=('gamification.entity',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamification.entity')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='team')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'db_table': 'teams',
            },
            bases=('gamification.entity',),
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(blank=True, default=False, null=True, verbose_name='reward fulfilled')),
                ('date_purchased', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date purchased')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user reward',
                'verbose_name_plural': 'user rewards',
                'db_table': 'user_reward',
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('hints', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.course')),
            ],
            options={
                'verbose_name': 'trivia',
                'verbose_name_plural': 'trivias',
                'db_table': 'trivia',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('type_name', models.CharField(default='Assignment', max_length=200)),
                ('type_icon', models.CharField(default='fa-solid fa-book', max_length=100)),
                ('mandatory', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'todo_list',
                'verbose_name_plural': 'todo_lists',
                'db_table': 'todo_list',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('colorBgBase', models.CharField(blank=True, max_length=7, verbose_name='Background color')),
                ('colorTextBase', models.CharField(blank=True, max_length=7, verbose_name='Text color')),
                ('colorPrimary', models.CharField(blank=True, max_length=7, verbose_name='Primary color')),
                ('colorSuccess', models.CharField(blank=True, max_length=7, verbose_name='Success color')),
                ('colorWarning', models.CharField(blank=True, max_length=7, verbose_name='Warning color')),
                ('colorError', models.CharField(blank=True, max_length=7, verbose_name='Error color')),
                ('cursor', models.ImageField(blank=True, upload_to='theme/cursor', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='cursor icon')),
                ('multiple_choice_item', models.ImageField(blank=True, upload_to='theme/multiple_choice_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple choice item')),
                ('multiple_choice_target', models.ImageField(blank=True, upload_to='theme/multiple_choice_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple choice target')),
                ('multiple_select_item', models.ImageField(blank=True, upload_to='theme/multiple_select_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple select item')),
                ('multiple_select_target', models.ImageField(blank=True, upload_to='theme/multiple_select_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple select target')),
                ('scale_multiple_choice_item', models.ImageField(blank=True, upload_to='theme/scale_multiple_choice_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='scale multiple choice item')),
                ('scale_multiple_choice_target', models.ImageField(blank=True, upload_to='theme/scale_multiple_choice_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='scale multiple choice target')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'theme',
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.feedbacksurvey')),
            ],
            options={
                'verbose_name': 'survey section',
                'verbose_name_plural': 'survey sections',
                'db_table': 'survey_section',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, null=True, verbose_name='points')),
                ('course_experience', models.IntegerField(default=0, null=True, verbose_name='points')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('question_type', models.TextField(choices=[('MULTIPLETEXT', 'Multipletext'), ('FIXEDTEXT', 'Fixedtext'), ('MULTIPLECHOICE', 'Multiplechoice'), ('SLIDEREVIEW', 'Slidereview'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('SCALEMULTIPLECHOICE', 'Scalemultiplechoice'), ('MULTIPLESELECT', 'Multipleselect')], default='MULTIPLECHOICE')),
                ('number_of_scale', models.IntegerField(blank=True, default=5, null=True)),
                ('number_of_text', models.PositiveIntegerField(default=1)),
                ('gamified', models.BooleanField(default=True)),
                ('phrased_positively', models.BooleanField(default=True)),
                ('min', models.IntegerField(blank=True, default=0, null=True)),
                ('max', models.IntegerField(blank=True, default=100, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.surveysection')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.question')),
            ],
            options={
                'verbose_name': 'option choice',
                'verbose_name_plural': 'option choices',
                'db_table': 'option_choice',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, choices=[('FEEDBACK_REQUEST', 'Feedback Request'), ('FEEDBACK_RESPONSE', 'Feedback Response'), ('POKE', 'Poke')], default='POKE')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.entity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.registration')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'membership',
                'db_table': 'membership',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='registration',
            field=models.ManyToManyField(through='gamification.Membership', to='gamification.Registration'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(through='gamification.Registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.course'),
        ),
        migrations.CreateModel(
            name='ArtifactReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('REOPEN', 'Reopen'), ('OPTIONAL_INCOMPLETE', 'Optional Incomplete'), ('LATE', 'Late')], default='INCOMPLETE')),
                ('trivia_completed', models.BooleanField(default=False)),
                ('artifact_review_score', models.IntegerField(blank=True, default=None, null=True)),
                ('max_artifact_review_score', models.IntegerField(blank=True, default=None, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.artifact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.registration')),
            ],
            options={
                'verbose_name': 'artifact_review',
                'verbose_name_plural': 'artifact_reviews',
                'db_table': 'artifact_review',
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.assignment'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.entity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='artifact_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.artifactreview'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.optionchoice'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.theme'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
