# Generated by Django 3.2 on 2024-03-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactreview',
            name='trivia_completed',
        ),
    ]
