# Generated by Django 3.2 on 2022-07-13 08:22

from django.db import migrations


def change_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site(name='Gamification Platform',
                domain='gamification-platform.herokuapp.com')
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_site_name),
    ]
