# Generated by Django 3.2 on 2023-04-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_xppoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xppoints',
            old_name='points',
            new_name='exp_points',
        ),
    ]
