# Generated by Django 3.2 on 2023-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_xppoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ipsatization_max',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ipsatization_min',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
