# Generated by Django 3.2 on 2024-03-22 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_artifactreview_trivia_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.trivia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user trivia',
                'verbose_name_plural': 'user trivia',
                'db_table': 'user_trivia',
            },
        ),
    ]
