# Generated by Django 3.2 on 2024-03-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_usertrivia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertrivia',
            unique_together={('user', 'trivia')},
        ),
    ]
