# Generated by Django 3.2 on 2022-08-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20220727_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactFeedback',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gamification.answer')),
                ('page', models.CharField(blank=True, max_length=150, verbose_name='page')),
            ],
            options={
                'verbose_name': 'artifact_feedback',
                'verbose_name_plural': 'artifact_feedback',
                'db_table': 'artifact_feedback',
            },
            bases=('gamification.answer',),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answerText',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='questionOption',
            new_name='question_option',
        ),
        migrations.RenameField(
            model_name='artifactreview',
            old_name='regisration',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='registration',
        ),
        migrations.AddField(
            model_name='answer',
            name='artifact_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamification.artifactreview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('MULTIPLETEXT', 'Multipletext'), ('FIXEDTEXT', 'Fixedtext'), ('MULTIPLECHOICE', 'Multiplechoice'), ('SLIDEREVIEW', 'Slidereview')], default='MULTIPLECHOICE'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
