# Generated by Django 3.2 on 2023-04-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20230410_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xppoints',
            old_name='points',
            new_name='exp_points',
        ),
    ]
