# Generated by Django 3.2 on 2023-04-16 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_rename_points_xppoints_exp_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], default='GET')),
                ('api', models.TextField(default='', verbose_name='api')),
                ('points', models.IntegerField(default=0, null=True, verbose_name='points')),
            ],
            options={
                'verbose_name': 'behaviors',
                'verbose_name_plural': 'behaviors',
                'db_table': 'behaviors',
            },
        ),
        migrations.CreateModel(
            name='ExpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], default='GET')),
                ('api', models.TextField(default='', verbose_name='api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exp history',
                'verbose_name_plural': 'exp histories',
                'db_table': 'exp_history',
            },
        ),
    ]
