# Generated by Django 3.2 on 2022-08-08 04:47

import app.gamification.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20220802_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), app.gamification.models.user.FileSizeValidator(max_size=5242880)], verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('MULTIPLETEXT', 'Multipletext'), ('FIXEDTEXT', 'Fixedtext'), ('MULTIPLECHOICE', 'Multiplechoice'), ('SLIDEREVIEW', 'Slidereview'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number')], default='MULTIPLECHOICE'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='number_of_text',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('type_name', models.CharField(default='Assignment', max_length=200)),
                ('type_icon', models.CharField(default='fa-solid fa-book', max_length=100)),
                ('mandatory', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'todo_list',
                'verbose_name_plural': 'todo_lists',
                'db_table': 'todo_list',
            },
        ),
    ]
