# Generated by Django 3.2 on 2022-08-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_auto_20220808_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
