# Generated by Django 3.2 on 2023-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_behavior_exphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='api',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='method',
        ),
        migrations.AddField(
            model_name='behavior',
            name='operation',
            field=models.TextField(default='', verbose_name='operation'),
        ),
    ]
