# Generated by Django 3.2 on 2022-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_auto_20220810_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreview',
            name='status',
            field=models.TextField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('LATE', 'Late')], default='INCOMPLETE'),
        ),
    ]
