# Generated by Django 3.2 on 2023-04-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_auto_20230416_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='constraint_ptr',
        ),
        migrations.RemoveField(
            model_name='courserule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courserule',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='point',
            name='constraint_ptr',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ruleconstraint',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='ruleconstraint',
            name='rule',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='CourseRule',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='RuleConstraint',
        ),
    ]
