# Generated by Django 3.2 on 2023-05-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20230423_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='artifact',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
