# Generated by Django 3.2 on 2022-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_auto_20221206_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='cur_point',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
