# Generated by Django 3.2 on 2023-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_auto_20230503_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xppoints',
            name='user',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ExpHistory',
        ),
        migrations.DeleteModel(
            name='XpPoints',
        ),
    ]
