# Generated by Django 3.2 on 2023-03-14 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_constraint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='update time')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.artifact')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='update time')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.grade')),
            ],
            options={
                'verbose_name': 'deduction',
                'verbose_name_plural': 'deductions',
                'db_table': 'deduction',
            },
        ),
    ]
