# Generated by Django 3.2 on 2023-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_auto_20230503_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='points',
            field=models.IntegerField(default=0, null=True, verbose_name='points'),
        ),
    ]
