# Generated by Django 3.2 on 2023-03-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_deduction_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
