# Generated by Django 3.2 on 2023-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_registration_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='fulfilled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='reward fulfilled'),
        ),
    ]
