# Generated by Django 3.2 on 2023-03-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0012_grade_grade_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='curved_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
