# Generated by Django 3.2 on 2023-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0012_userreward_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.TextField(choices=[('Other', 'Other'), ('Late Submission', 'Late Submission'), ('Bonus', 'Bonus')]),
        ),
        migrations.DeleteModel(
            name='RewardType',
        ),
    ]
