# Generated by Django 3.2 on 2023-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0013_auto_20230319_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreview',
            name='artifact_review_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='artifactreview',
            name='max_artifact_review_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
