# Generated by Django 3.2 on 2023-05-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0014_auto_20230517_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorBgBase', models.CharField(blank=True, max_length=7, verbose_name='Background color')),
                ('colorTextBase', models.CharField(blank=True, max_length=7, verbose_name='Text color')),
                ('colorPrimary', models.CharField(blank=True, max_length=7, verbose_name='Primary color')),
                ('colorSuccess', models.CharField(blank=True, max_length=7, verbose_name='Success color')),
                ('colorWarning', models.CharField(blank=True, max_length=7, verbose_name='Warning color')),
                ('colorError', models.CharField(blank=True, max_length=7, verbose_name='Error color')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'theme',
                'db_table': 'theme',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.theme'),
        ),
    ]
