# Generated by Django 3.2 on 2023-05-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0016_auto_20230525_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='cursor',
            field=models.CharField(blank=True, max_length=15, verbose_name='Cursor'),
        ),
    ]
