# Generated by Django 3.2 on 2023-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0017_theme_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='multiple_choice',
            field=models.CharField(blank=True, default='nature', max_length=15, verbose_name='Multiple Choice'),
        ),
    ]
