# Generated by Django 3.2 on 2023-05-31 16:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0019_userreward_date_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('hints', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
            ],
            options={
                'verbose_name': 'trivia',
                'verbose_name_plural': 'trivias',
                'db_table': 'trivia',
            },
        ),
        migrations.AddField(
            model_name='feedbacksurvey',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.trivia'),
        ),
    ]
