# Generated by Django 3.2 on 2023-06-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0022_artifactreview_trivia_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='feedbacksurvey',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='surveysection',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='other_info',
        ),
    ]
