# Generated by Django 3.2 on 2023-06-08 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0023_auto_20230607_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='multiple_choice',
        ),
        migrations.AddField(
            model_name='theme',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_choice_icon',
            field=models.ImageField(blank=True, upload_to='theme/multiple_choice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='cursor icon'),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_select_icon',
            field=models.ImageField(blank=True, upload_to='theme/multiple_select', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple select icon'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='scale_multiple_choice_icon',
            field=models.ImageField(blank=True, upload_to='theme/scale_multiple_choice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='scale multiple choice icon'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cursor',
            field=models.ImageField(blank=True, upload_to='theme/cursor', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='cursor icon'),
        ),
    ]
