# Generated by Django 3.2 on 2023-06-08 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0024_auto_20230607_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='multiple_choice_icon',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='multiple_select_icon',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='scale_multiple_choice_icon',
        ),
        migrations.AddField(
            model_name='theme',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_choice_item',
            field=models.ImageField(blank=True, upload_to='theme/multiple_choice_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple choice item'),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_choice_target',
            field=models.ImageField(blank=True, upload_to='theme/multiple_choice_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple choice target'),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_select_item',
            field=models.ImageField(blank=True, upload_to='theme/multiple_select_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple select item'),
        ),
        migrations.AddField(
            model_name='theme',
            name='multiple_select_target',
            field=models.ImageField(blank=True, upload_to='theme/multiple_select_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='multiple select target'),
        ),
        migrations.AddField(
            model_name='theme',
            name='scale_multiple_choice_item',
            field=models.ImageField(blank=True, upload_to='theme/scale_multiple_choice_item', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='scale multiple choice item'),
        ),
        migrations.AddField(
            model_name='theme',
            name='scale_multiple_choice_target',
            field=models.ImageField(blank=True, upload_to='theme/scale_multiple_choice_target', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='scale multiple choice target'),
        ),
    ]
