# Generated by Django 3.2 on 2023-06-11 23:58

import app.gamification.models.course
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0025_auto_20230608_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to=app.gamification.models.course.Course.photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), app.gamification.models.course.FileSizeValidator(max_size=5242880)], verbose_name='course picture'),
        ),
    ]
