# Generated by Django 3.2 on 2023-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0026_alter_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
