# Generated by Django 3.2 on 2023-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0027_auto_20230625_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_experience',
            field=models.IntegerField(default=0, null=True, verbose_name='points'),
        ),
    ]
