# Generated by Django 3.2 on 2023-07-14 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0030_auto_20230712_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_streak',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='daily streak'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last login'),
        ),
    ]
