# Generated by Django 3.2 on 2023-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0031_auto_20230714_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.TextField(blank=True, choices=[('FEEDBACK_REQUEST', 'Feedback Request'), ('FEEDBACK_RESPONSE', 'Feedback Response'), ('POKE', 'Poke')], default='POKE'),
        ),
    ]
