# Generated by Django 3.2 on 2023-11-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0033_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='uploader_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='min_reviewers',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='artifactreview',
            name='status',
            field=models.TextField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('REOPEN', 'Reopen'), ('OPTIONAL_INCOMPLETE', 'Optional Incomplete'), ('LATE', 'Late')], default='INCOMPLETE'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gamification_mode',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='gamification mode'),
        ),
    ]
