# Generated by Django 3.2 on 2023-11-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0034_auto_20231107_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksurvey',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
