# Generated by Django 3.2 on 2024-02-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0035_feedbacksurvey_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.course'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
