# Generated by Django 3.2 on 2024-03-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0035_feedbacksurvey_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='trivia_completed',
            field=models.BooleanField(default=False),
        ),
    ]
