# Generated by Django 3.2 on 2024-03-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0035_feedbacksurvey_is_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactreview',
            name='trivia_completed',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='trivia',
        ),
        migrations.AddField(
            model_name='course',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.trivia'),
        ),
        migrations.AddField(
            model_name='course',
            name='trivia_completed',
            field=models.BooleanField(default=False),
        ),
    ]
