# Generated by Django 3.2 on 2024-02-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0036_auto_20240219_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into admin site.', verbose_name='staff status'),
        ),
    ]
