# Generated by Django 3.2 on 2024-03-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0036_auto_20240309_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trivia_completed',
        ),
    ]
