# Generated by Django 3.2 on 2024-03-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0036_auto_20240310_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
